### PR TITLE
Add diagram for the "qrexec3 basics" section of qrexec3.md

### PR DESCRIPTION
**Pull request by pierwill**
This diagram is meant to give the reader a **general** picture of Qubes remote execution, before diving into the specifics of the framework. It will appear in the "basics" section [here](https://www.qubes-os.org/doc/qrexec3/#qrexec-basics).

This diagram was made incorporating feedback from the discussion in https://github.com/QubesOS/qubes-doc/pull/847.

This version was generated with the [mermaidjs web app](https://mermaidjs.github.io/mermaid-live-editor/) using the following code:

```
graph LR
    subgraph someVM
    A[qrexec-agent]
    end
    subgraph dom0
    C[qrexec-client]
    B[qrexec-daemon]
    C -->|initial request| B
    B -->|relayed request| A
    B -. vchan details .-> C
    B -. vchan details .-> A
    end
    C -->|established vchan channel| A
```

Comments and suggestions would be greatly appreciated!

### CODE REVIEW

**Comment by pierwill** [comment]
Here's a rough png screencap preview:
Screenshot-2019-8-9 Online FlowChart Diagrams Editor - Mermaid Live Editor

**Comment by marmarek** [comment]
Please add source somewhere into git. Preferably another file besides svg, but even commit message would be an improvement. Pull request description live only on github servers and is not part of the actual git repository.

**Comment by andrewdavidwong** [comment]
> Please add source somewhere into git. Preferably another file besides svg, but even commit message would be an improvement. Pull request description live only on github servers and is not part of the actual git repository.

Perhaps another file alongside this one called `qrexec3-basics.mermaidjs`? (Or whatever's the standard file extension for such files, if there is one.)

**Comment by pierwill** [comment]
Good ideas, thanks! I'll push a commit with source and instructions on building the diagram.

**Pull request merged**
