### PR TITLE
New diagrams for qrexec-internals

### PR DESCRIPTION
**Pull request by pwmarcz**

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
Linked PR: https://github.com/QubesOS/qubes-doc/pull/937

**Comment by pwmarcz** [comment]
>I assume those diagrams are the one I've seen before.

Compared to what I showed you, I fixed a few mistakes (and flipped one left-to-right).

>Also, as we've already established, you already know qrexec better than me @pwmarcz ;)

Well I could use a quick sanity check at least :)

**Comment by marmarek** [comment]
Yes, I've checked the diagrams again and looks fine.
One thing that may not be clear (from diagrams alone) is in case of service call that "cmd" is actually "QUBESRPC service.name source-domain". But since diagrams focus on qrexec messages, not services built on top of qrexec, that can be explained outside of the diagrams.

**Comment by marmarek** [comment]
Do _you_ need to restore your sanity points? ;)

**Comment by pwmarcz** [comment]
>QUBESRPC service.name source-domain

I did not know that! I remember seeing a part that handles `QUBESRPC` so I know it's a part of qrexec. But I agree, maybe that's too much information to stuff in these diagrams. Not enough sanity points.

**Pull request merged**
