### PR TITLE
Add README

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Ref https://github.com/QubesOS/qubes-issues/issues/4260.

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
Pushed some changes. Note: Please use `.md` instead of `.mediawiki`.

I have some questions about the commented-out lines:

- Is the copyright notice necessary? It will be a pain to manually update it across all repos every year.
- What's the rationale behind the editor's note? Where else would someone be editing the README and using relative links?

**Comment by adrelanos** [comment]
I don't think it is a problem if contributor years lag behind a few years. Not if/when lack of not updating the copyright year becomes a problem.

Using custom license headers might conflict with this https://www.qubes-os.org/doc/license/ since that somehow implies a special situation not covered by that.

**Comment by andrewdavidwong** [comment]
> I don't think it is a problem if contributor years lag behind a few years.

Ok.

> Not if/when lack of not updating the copyright year becomes a problem.

Sorry, I don't understand. What do you mean?

> Using custom license headers might conflict with this https://www.qubes-os.org/doc/license/ since that somehow implies a special situation not covered by that.

Sorry, I'm not tracking what the two "that"s refer to. Could you explain a bit more verbosely?

**Comment by tapaswenipathak** [comment]
> Pushed some changes. Note: Please use .md instead of .mediawiki.

Using `.md` instead of `.mediawiki` will make that readme unreadable. Sample commit d42e46d. 

> I have some questions about the commented-out lines:

> - Is the copyright notice necessary? It will be a pain to manually update it across all repos every year.

Legally yes, functionally no. Fixing the year can be automated, there are packages which can do that.

> - What's the rationale behind the editor's note? Where else would someone be editing the README and using relative links?

You should be following certain rules, behavior if you require README editing. Please find the info on - https://www.mediawiki.org/wiki/Help.

**Comment by andrewdavidwong** [comment]
> > Pushed some changes. Note: Please use .md instead of .mediawiki.
> 
> Using `.md` instead of `.mediawiki` will make that readme unreadable, useless on GitHub. Sample commit [d42e46d](https://github.com/QubesOS/qubes-attachment/commit/d42e46d2d6f03ccb6cdf89328f60dff8506c426f).
> 

No, I'm asking you to write in Markdown instead of MediaWiki markup. All of our docs are written in Markdown, not MediaWiki markup.

I already made these changes for you. I'm just asking you to do the same in any future commits and PRs.

> > I have some questions about the commented-out lines:
> 
> > * Is the copyright notice necessary? It will be a pain to manually update it across all repos every year.
> 
> Legally yes, functionally no. Fixing the year can be automated, there are packages which can do that.
> 

I don't believe the notice is legally necessary in most jurisdictions.

> > * What's the rationale behind the editor's note? Where else would someone be editing the README and using relative links?
> 
> You should be following certain rules, behavior if you require README editing. Please find the info on - https://www.mediawiki.org/wiki/Help.


I don't understand what you mean. I'm saying that people will only be editing the README in a local checkout or on GitHub. In either case, it doesn't seem likely that an editor would use relative links, and we've never had that problem before.

Why is the MediaWiki Help page relevant here? We don't use MediaWiki for anything in this project.

**Comment by andrewdavidwong** [comment]
@tapaswenipathak: I sincerely appreciate the effort you're making to contribute PRs, but the time required to review each one is turning out to be far longer than usual and longer than it would take the write the content ourselves. In light of this, I'm afraid I have to decline this PR.

**Comment by tapaswenipathak** [comment]
@andrewdavidwong As discussed in https://github.com/QubesOS/qubes-vmm-xen/pull/57#issuecomment-511894345, after merging few READMEs the effort would be less. @marmarek told that I should write as per whonix README. Right now the topic is still what format the readme should have. You can't have Whonix README file structure until you write in `.mediawiki` format. `.md` formatting would show TOC v. differently, which is I initially submitted, what is your stand?

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong As discussed in [QubesOS/qubes-vmm-xen#57 (comment)](https://github.com/QubesOS/qubes-vmm-xen/pull/57#issuecomment-511894345), after merging few READMEs the effort would be less. @marmarek told that I should write as per whonix README. Right now the topic is still what format the readme should have. You can't have Whonix README file structure until you write in `.mediawiki` format. `.md` formatting would show TOC v. differently, which is I initially submitted, what is your stand?

Ah, perhaps there was a misunderstanding. @marmarek also requested Markdown instead of MediaWiki in https://github.com/QubesOS/qubes-linux-dom0-updates/pull/3#pullrequestreview-264513838.

**Comment by tapaswenipathak** [comment]
>> @andrewdavidwong As discussed in QubesOS/qubes-vmm-xen#57 (comment), after merging few READMEs the effort would be less. @marmarek told that I should write as per whonix README. Right now the topic is still what format the readme should have. You can't have Whonix README file structure until you write in .mediawiki format. .md formatting would show TOC v. differently, which is I initially submitted, what is your stand?

> Ah, perhaps there was a misunderstanding. @marmarek also requested Markdown instead of MediaWiki in QubesOS/qubes-linux-dom0-updates#3 (review).

Yea but now different than what he previously spoke, re - https://github.com/QubesOS/qubes-vmm-xen/pull/57#issuecomment-512634801. No problem, happens. We have a decision of the format of the file. Frankly, I have no issues in keeping this PR closed.

**Comment by adrelanos** [comment]
Andrew David Wong:
>> Not if/when lack of not updating the copyright year becomes a problem.
> 
> Sorry, I don't understand. What do you mean?


It's related to when the copyright ceases to exist and the work becomes
part of the public domain.

https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html

>> Using custom license headers might conflict with this https://www.qubes-os.org/doc/license/ since that somehow implies a special situation not covered by that.
> 
> Sorry, I'm not tracking what the two "that"s refer to. Could you explain a bit more verbosely?


https://www.qubes-os.org/doc/license/ is supposed to be the conditions
for contribution to Qubes. Everyone who follows the usual process, as
the theory goes, is accepting these conditions.

Now, when someone sends a contribution with a custom licensing header
which hasn't been ever uses before within the project, then it could be
argued this contributor wasn't aware of
https://www.qubes-os.org/doc/license/ and/or
https://www.qubes-os.org/doc/license/ does not apply.

**Comment by adrelanos** [comment]
>> Legally yes, functionally no. Fixing the year can be automated, there are packages which can do that.
>>
> 
> I don't believe the notice is legally necessary in most jurisdictions.


https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html says:

> You should maintain a proper copyright notice and a license notice in
each nontrivial file in the package.

Note: I am not arguing this specific pull request should be merged.
Rather just weighing in on these auxiliary parts.

But "necessary" can mean many things. In worst case, someone could argue
it makes it nonfree.

Quote FSF:

> This page is maintained by the Free Software If you have questions
about free software licenses, you can email us at <licensing@fsf.org>.

**Comment by andrewdavidwong** [comment]
Thank you for the information, @adrelanos!

I am not a lawyer, so I have no idea what is legally required or
appropriate in this case. I am happy to do whatever the law requires and
whatever is in the best interest of the Qubes OS Project, its users, and
its contributors.

I will leave it up to @marmarek and @MiCh to decide whether to consult a
lawyer or what is the best course of action for the project.

Thank you for your efforts and for caring! :)

**Pull request closed without merging**
